### PR TITLE
Use absolute paths to support opening files outside workspace. 

### PR DESCRIPTION
**Pull request by Osmose**
One of my main use cases for making advanced-open-file was to easily open files outside the active workspace. To support this, we need to use absolute paths in the input at the top of the dialog.

Along with refactoring to use absolute paths instead of relative paths, this adds a ".." file at the top of non-root directories to make moving up a directory easier.

This is based off #3 because the octicons happen to sort directories to the top of the listing. Without them, directories are sorted alphabetically with the rest of the files. The second commit in this PR contains the main changes.

Screen Shot 2019-06-17 at 9 52 37 PM

### CODE REVIEW

**Comment by Osmose** [comment]
Just noticed I left a lot of semicolons and a comma, whoops. I'll fix them to match the surrounding style along with whatever review fixes come up.

**Comment by Osmose** [comment]
Updated, rebased on the updated #3, and prettiered!

**Comment by jit-y** [comment]
Thank you!
But it seems there are some conflicts due to have merged #3...;(
Please fix them, and after that I'll merge this!

**Comment by Osmose** [comment]
Rebased. Weirdly it had no conflicts when I rebased locally. Dunno what Github was on about.

**Comment by jit-y** [comment]
This has been released and published!

https://github.com/jit-y/vscode-advanced-open-file/releases/tag/v0.1.7

**Comment by Osmose** [comment]
🎉 Thanks!

**Pull request merged**
